### ISSUE TITLE
Create a nuget package and upload it to nuget.org

### ISSUE THREAD

**Issue by izrik** [FreeApophis/ircddotnet#2]
If IrcD.Net were available as a package from [nuget](https://www.nuget.org), then it could be used in unit tests for irc client libraries. I've done this sort of thing before, and would be willing to help.

**Comment by FreeApophis** [comment]
I have never created a NuGet package before, but if it is as easy as creating a gem in Ruby-World I would give it a try.

Any specific wishes, or things I should keep in mind?
I'll try this Manual: https://docs.nuget.org/create/creating-and-publishing-a-package

**Comment by izrik** [comment]
Yeah, that guide is good. I have a few 3d game projects with nuget pakages. Here are the nuspec files: [FbxSharp](https://github.com/izrik/FbxSharp/blob/master/FbxSharp.nuspec), [ChamberLib](https://github.com/izrik/ChamberLib/blob/master/ChamberLib.nuspec), [ChamberLib.FbxSharp](https://github.com/izrik/ChamberLib.FbxSharp/blob/master/ChamberLib.FbxSharp.nuspec).

The premise is pretty simple. The xml file describes the package, it's id, name, version, authors, release notes, etc. Once the nuspec file is created and everything has been set up on the nuget.org site, you can just run the `nuget pack` and `nuget push` commands to create and upload the package. I even have a script that does it all from a Travis-CI build, [here](https://github.com/izrik/FbxSharp/blob/master/nuget-pack-push.sh) and [here](https://github.com/izrik/FbxSharp/blob/master/.travis.yml#L20).

I'm planning to use it as an embedded server in tests for an IRC client library. For that, all that I would need would be the `IrcD.Net.dll` file. Admittedly, I am not sure about whether including the `IrcD.Server.exe` file would be useful. I have no experience with using nuget for distributing actual application, just libraries. I think [Chocolatey](https://chocolatey.org/) would be the tool for that, but I have no experience with it.

**Comment by FreeApophis** [comment]
Bumped Version to 0.6 and pushed a NuGet Package here:
https://www.nuget.org/packages/IrcD.Net/

**Comment by izrik** [comment]
Sweet! Thanks a lot! =)
