### ISSUE TITLE
LIST contains channels with 0 users

### ISSUE THREAD

**Issue by FunkyFr3sh** [FreeApophis/ircddotnet#3]
Ghost channels remain in LIST if a user quits the server while he was alone in a channel

**Comment by FreeApophis** [comment]
I could reproduce the behaviour, The removal of a user was handled differently for each case of user leaving the channel [Part, Kick, Quit, Kill and Connection Lost]. This correct behaviour from the Part message was now moved to ChannelInfo.RemoveUser(user). 

Minimal testing - but it seems to resolve the Problem.
