### ISSUE TITLE
License file and license headers in code do not match

### ISSUE THREAD

**Issue by marius-klimantavicius** [FreeApophis/ircddotnet#5]
LICENSE file in the root of repository claims project to be BSD 3-clause licensed. However looking into code I see license headers saying that the license is GPL-3. Please clarify the license, preferably either by updating LICENSE file or license headers in code. IANAL but I guess it should be enough to resolve the license conflict in the readme.

**Comment by FreeApophis** [comment]
That's probably because I do not care that much anymore than I did when I started this project.

It's BSD-3 - I updated the headers.

Thanks for pointing it out.
